#!/usr/bin/env bash
#Custom HTTP Header for web-01 and web-02

apt-get -y update
apt-get -y install nginx

# is used to allow incoming connections to the Nginx HTTP server through the firewall through port 80. using the ufw (Uncomplicated Firewall) command-line tool.
sudo ufw allow 'Nginx HTTP'

echo 'Hello World!' > /var/www/html/index.html

sudo sed -i '24i\rewrite ^/redirect_me https://github.com/TemiladeRebecca permanent;' /etc/nginx/sites-enabled/default

# Set up a 404 page
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\       error_page 404 /error_404.html;' /etc/nginx/sites-enabled/default

# Setting up custom HTTP header called 'X-Served-By' to all responses, containing the hostname of the server that served the request.
sudo sed -i '/server_name _/a add_header X-Served-By $hostname;' /etc/nginx/sites-enabled/default

service nginx restart
